# --------------------------------
# Site settings
title: Hub3C
slogan: Connect. Communicate. Collaborate.
author: Ben Anggoro
email: ben@benworkandplay.com
project: Hub3C for Geekseat.com.au
description: > # this means to ignore newlines until "baseurl:"
  Landing page prototype for Hub3C marketing website

# --------------------------------
# Environment Settings
environment: production
baseurl: "/" # the subpath of your site, e.g. /blog/
url: ""
source: project
destination: _dist

# --------------------------------
# Build settings
markdown: kramdown
safe: false
future: true
permalink: pretty

# Includes & Excludes
collections:
- home-sections
